// Generated by CoffeeScript 1.6.3
(function() {
  var app, express, human, logger, nodemailer, port, smtpTransport;

  express = require("express");

  nodemailer = require("nodemailer");

  logger = require('caterpillar').createLogger();

  human = require('caterpillar-human').createHuman();

  logger.pipe(human).pipe(require('fs').createWriteStream('./debug.log'));

  app = express();

  app.use(express.json());

  app.use(express.urlencoded());

  app.use(require('express-validator')());

  smtpTransport = nodemailer.createTransport("SMTP", {
    host: "mail.google.com",
    port: 25
  });

  /* setup e-mail data with unicode symbols
  mailOptions =
      from: "Fred Foo ✔ <foo@blurdybloop.com>" # sender address
      to: "bar@blurdybloop.com, baz@blurdybloop.com" # list of receivers
      subject: "Hello ✔" # Subject line
      text: "Hello world ✔" # plaintext body
      html: "<b>Hello world ✔</b>" # html body
  */


  app.post("/send-email", function(req, res) {
    req.sanitize('from').toString();
    req.sanitize('to').toString();
    req.sanitize('subject').toString();
    req.sanitize('text').toString();
    req.sanitize('html').toString();
    return smtpTransport.sendMail(req.body, function(error, response) {
      if (error) {
        logger.log("alert", error);
        return res.json(300, {
          result: error
        });
      } else {
        logger.log("info", "Message sent: " + response.message);
        return res.json(200, {
          result: response.message
        });
      }
    });
  });

  port = process.env.PORT || 5000;

  app.listen(port, 'localhost', function() {
    return logger.log("info", "Starting up and listening on " + port);
  });

}).call(this);
